base_url = "https://kafkaa.xyz/"
compile_sass = false
minify_html = true
generate_feeds = true
default_language = "en"
author = 'Manoprasanth MATHAVAN'
taxonomies = [
    {name = "tags", feed = false},
]

[languages.fr]
# weight = 2
# languageName = "Français"
# languageCode = "fr"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Manoprasanth MATHAVAN"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "dark"
list_pages = false
twitter_card = false

header_nav = [
  { url = "/", name_en = "Home", name_fr = "/accueil/" },
  { url = "/blog", name_en = "Blog", name_fr = "/blog" },
  { url = "/readinglog", name_en = "Books", name_fr = "/livres" },
#  { url = "/quotes", name_en = "/quotes", name_fr = "/notes" },
  { url = "/about", name_en = "About", name_fr = "/concernant" }
]
